### ISSUE TITLE
DaemonSet should not assume it must be deployed to all worker nodes or into a single role

### ISSUE THREAD

**Issue by williamcaban** [openshift/sriov-network-operator#32]
The current nodeSelector for the DaemonSet match all worker nodes
 
https://github.com/openshift/sriov-network-operator/blob/master/bindata/manifests/daemon/daemonset.yaml#L25-L27

1. This approach limit the ability to use the operator in environment with multiple worker roles (e.g. worker-gpu, worker-rt, worker-group-a, etc)
2. This approach may deploy the DaemonSet into Nodes that do not require or support SRIOV. For example, environment with worker nodes where some may have NIC cards with support for SRIOV and other nodes in the same role which doesn't.

Consider the use of a custom node label to determine the Nodes into which to deploy the DaemonSet. (e.g. `sriov.openshift.io=true`)

**Comment by pliurh** [comment]
The reason why the  daemonset is deployed on all worker node is that, we want the daemon to discover the SRIOV hardware info among the whole cluster. So that, users can know where they are able to deploy the SRIOV CNI plugin and device plugin. It doesn't mean you have to deploy the SRIOV CNI plugin and device plugin, or run SRIOV workload on every node.

**Comment by williamcaban** [comment]
I understand that reasoning behind number 2. It is still not the desired behavior when configuring nodes with real-time kernel where reservations and allocations of millicores for platform components and non-real-time workloads must be as low as possible. In those scenarios, unused components should be avoided in the nodes. This is the case when configuring workers for 5G mobile core components, remote CPE/NTD nodes, etc, where the number of available cores are an extremely valuable resource and should be protected for the real-time workloads. Ideally, the reservations should be less than 1 core in real-time nodes. This is more a Telco & MSO specific use case. At least the default deployment behavior should be documented.

Point number 1 might be far more important to document. If the cluster has multiple types of worker nodes (for example, regular workers only used for platform components like registry, OCP routers, etc., and other types of workers like "worker-rt", "worker-rhel8", "worker-pci" for other purposes), the operator only deploy to "worker" and not to any of the other types.

**Comment by fepan** [comment]
One way to address the need for different worker roles (worker-rt, worker-rhel8, etc) is to use nodeselector when deploying the pods, so that the required workload will only be scheduled at nodes that fits. This has the added benefit of being able to deploy multiple types of SR-IOV workloads to different kinds of SR-IOV nodes as well; the device plugin should just be managing the available resource (VF).

For cases where it is truly undesirable or harmful to deploy SR-IOV device plugin on certain nodes but not others, we'll need some concrete customer use cases and requirements before we would consider adding this capability, as this does add complexity to the implementation. When we first started implementation, early customer feedback had mostly been that they would be running a uniform cluster and there was no desire to treat nodes differently.

**Comment by pliurh** [comment]
For the realtime case, I think the better way to avoid deploying no-RT workload on RT node, could be taint RT nodes with something like 'node.openshift.io/realtime'. So that pods without matched toleration would not be deployed on those nodes. The pro is that it works for all pods. You don't need to worry any unwelcome daemonset or other controllers which schedule pod to the RT nodes.

**Comment by williamcaban** [comment]
@fepan Wouldn't this prevent the use of other nodeSelector different from "worker"?

https://github.com/openshift/sriov-network-operator/blob/master/pkg/controller/sriovnetworknodepolicy/sriovnetworknodepolicy_controller.go#L125-L136

**Comment by fepan** [comment]
A worker label should not preclude other labels from being applied for a node, like worker-rt. So a node can be both a worker (so that SR-IOV device plugin is deployed) and a worker-rt (where a RT workload can be deployed)

**Comment by williamcaban** [comment]
We are seeing behavior in which worker nodes with more than one node type label get into a state where both labels conflict (even in a parent-child definition), so we cannot maintain two node-type labels. In those scenarios, the SRIOV operator does not work for the other nodes.

What other options can we use here? What about having the operator deploy to all types of nodes != master?

**Comment by pliurh** [comment]
We plan to support deploying config daemon to node with custom roles in next release.

**Comment by pliurh** [comment]
closed by #106
