### ISSUE TITLE
Remove networkNamespace from SriovNetwork CRD

### ISSUE THREAD

**Issue by e0ne** [openshift/sriov-network-operator#492]
Since SriovNetwork CR is namespaced scope, it's not obvious to have resources in different namespaces. Let's remove networkNamespace field and use CR namespace instead of it

**Comment by zshi-redhat** [comment]
I remembered we had to add custom finalizer for net-attach-def cleanup due to a change of not be able to use cross-namespace owner reference (net-attach-def -> sriovnetwork). 
Not sure if we still have issue with the custom finalizer or not. /cc @pliurh 

It sounds reasonable to change the CR scope since we are using namespaced CR to manage resources in different namespaces.
