### ISSUE TITLE
Operator tries to modify grub configuration on a worker node

### ISSUE THREAD

**Issue by jellonek** [openshift/sriov-network-operator#541]
I understand that it's use simplification to make it easier for enduser, but IMO any kind of workload, even operator should not attempt to modify anything on host nodes where it is running.

My suggestion would be to instead trying to update grub configuration (which is btw. done purely, as not all RHEL installations have `grubby` installed and that's how i noticed that) there should be sent a message to the human operator that the node is improperly configured, and he/she should follow the documentation which could be found there and there. Also even "hidden under the hood" grub configuration update was done - still node has to be rebooted, so IMO what is happening now is broken on several different abstraction levels.

That could be done in logs, or/and by generating a kubernetes event.

**Comment by zshi-redhat** [comment]
@jellonek thanks for the issue and suggestions!

Yes, as you have indicated, our goal has been to simplify the configuration that enduser needs to do and provide end to end solution for sriov related configuration.

We have seem similar issues before that some configurations only apply to RHEL. It has reason that the project itself is originated from openshift. But we have been trying to make it available for other distros as well since it was moved under NPWG. One example is that we have added loading udev rule support for ubuntu : https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/bindata/scripts/load-udev.sh#L9.

I think another way we can solve this issue is to add support for the distro you are using. wdyt?
The operator reboots the node by itself, there is a systemd service that runs the reboot cmd.

I'd also like to hear how would you like to use this operator since you mentioned it breaks several different abstraction levels, my guess is that maybe you are using this Operator differently than what some of us are doing.

**Comment by jellonek** [comment]
Oh, I missed that the operator does the node reboot (that's even more evil that I thought :D ).

The point is - distro on which I seen this behavior was RHEL:
```
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

The operator (if configured properly and nodes are manually tuned properly) works fine. IMO only the node preparation is just broken from security perspective as the software is "escaping" from kubernetes abstraction to host nodes level and is changing kinda fundamental configuration - that should be at least described in capital letters on the README.md ;)
(yes, I know that other vendors especially in the area of CNI are doing similar things, but still - imo it's wrong and abusive use of easiness to escape from priviledged k8s container to the host)
